<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VkRadio.LowCode.AppGenerator.MetaModel\VkRadio.LowCode.AppGenerator.MetaModel.csproj" />
    <ProjectReference Include="..\VkRadio.LowCode.ArtefactGenerators.Core\VkRadio.LowCode.ArtefactGenerators.Core.csproj" />
  </ItemGroup>

</Project>
