using ArtefactGenerationProject.ArtefactGenerator.Ool.Abstract.Component;
using ArtefactGenerationProject.ArtefactGenerator.Ool.CSharp.Classic.Package.Root;

namespace ArtefactGenerationProject.ArtefactGenerator.Ool.CSharp.Classic.Component.Properties
{
    public class ResourcesDesigner: ComponentWPredefinedCode
    {
        public ResourcesDesigner(PropertiesPackageAbstract in_package)
        {
            Package = in_package;
            _emitUtf8Bom = true;
            Name = "Resources.Designer.cs";

            _predefinedCode.Add("//------------------------------------------------------------------------------");
            _predefinedCode.Add("// <auto-generated>");
            _predefinedCode.Add("//     This code was generated by a tool.");
            _predefinedCode.Add("//     Runtime Version:4.0.30319.42000");
            _predefinedCode.Add("//");
            _predefinedCode.Add("//     Changes to this file may cause incorrect behavior and will be lost if");
            _predefinedCode.Add("//     the code is regenerated.");
            _predefinedCode.Add("// </auto-generated>");
            _predefinedCode.Add("//------------------------------------------------------------------------------");
            _predefinedCode.Add(string.Empty);
            _predefinedCode.Add(string.Format("namespace {0}.Properties {{", in_package.ParentPackage.RootNamespace));
            _predefinedCode.Add("    using System;");
            _predefinedCode.Add("    ");
            _predefinedCode.Add("    ");
            _predefinedCode.Add("    /// <summary>");
            _predefinedCode.Add("    ///   A strongly-typed resource class, for looking up localized strings, etc.");
            _predefinedCode.Add("    /// </summary>");
            _predefinedCode.Add("    // This class was auto-generated by the StronglyTypedResourceBuilder");
            _predefinedCode.Add("    // class via a tool like ResGen or Visual Studio.");
            _predefinedCode.Add("    // To add or remove a member, edit your .ResX file then rerun ResGen");
            _predefinedCode.Add("    // with the /str option, or rebuild your VS project.");
            _predefinedCode.Add("    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"System.Resources.Tools.StronglyTypedResourceBuilder\", \"4.0.0.0\")]");
            _predefinedCode.Add("    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]");
            _predefinedCode.Add("    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]");
            _predefinedCode.Add("    internal class Resources {");
            _predefinedCode.Add("        ");
            _predefinedCode.Add("        private static global::System.Resources.ResourceManager resourceMan;");
            _predefinedCode.Add("        ");
            _predefinedCode.Add("        private static global::System.Globalization.CultureInfo resourceCulture;");
            _predefinedCode.Add("        ");
            _predefinedCode.Add("        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute(\"Microsoft.Performance\", \"CA1811:AvoidUncalledPrivateCode\")]");
            _predefinedCode.Add("        internal Resources() {");
            _predefinedCode.Add("        }");
            _predefinedCode.Add("        ");
            _predefinedCode.Add("        /// <summary>");
            _predefinedCode.Add("        ///   Returns the cached ResourceManager instance used by this class.");
            _predefinedCode.Add("        /// </summary>");
            _predefinedCode.Add("        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]");
            _predefinedCode.Add("        internal static global::System.Resources.ResourceManager ResourceManager {");
            _predefinedCode.Add("            get {");
            _predefinedCode.Add("                if ((resourceMan == null)) {");
            _predefinedCode.Add(string.Format("                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(\"{0}.Properties.Resources\", typeof(Resources).Assembly);", in_package.ParentPackage.RootNamespace));
            _predefinedCode.Add("                    resourceMan = temp;");
            _predefinedCode.Add("                }");
            _predefinedCode.Add("                return resourceMan;");
            _predefinedCode.Add("            }");
            _predefinedCode.Add("        }");
            _predefinedCode.Add("        ");
            _predefinedCode.Add("        /// <summary>");
            _predefinedCode.Add("        ///   Overrides the current thread's CurrentUICulture property for all");
            _predefinedCode.Add("        ///   resource lookups using this strongly typed resource class.");
            _predefinedCode.Add("        /// </summary>");
            _predefinedCode.Add("        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]");
            _predefinedCode.Add("        internal static global::System.Globalization.CultureInfo Culture {");
            _predefinedCode.Add("            get {");
            _predefinedCode.Add("                return resourceCulture;");
            _predefinedCode.Add("            }");
            _predefinedCode.Add("            set {");
            _predefinedCode.Add("                resourceCulture = value;");
            _predefinedCode.Add("            }");
            _predefinedCode.Add("        }");
            _predefinedCode.Add("    }");
            _predefinedCode.Add("}");
        }
    };
}
