using ArtefactGenerationProject.ArtefactGenerator.Ool.Abstract.Component;
using ArtefactGenerationProject.ArtefactGenerator.Ool.CSharp.Classic.Package.Root;

namespace ArtefactGenerationProject.ArtefactGenerator.Ool.CSharp.Classic.Component.Properties
{
    public class Resources: ComponentWPredefinedCode
    {
        public Resources(PropertiesPackageAbstract in_package)
        {
            Package = in_package;
            _emitUtf8Bom = true;
            _lastLineWNewLine = false;
            Name = "Resources.resx";

            _predefinedCode.Add("<?xml version=\"1.0\" encoding=\"utf-8\"?>");
            _predefinedCode.Add("<root>");
            _predefinedCode.Add("  <!-- ");
            _predefinedCode.Add("    Microsoft ResX Schema ");
            _predefinedCode.Add("    ");
            _predefinedCode.Add("    Version 2.0");
            _predefinedCode.Add("    ");
            _predefinedCode.Add("    The primary goals of this format is to allow a simple XML format ");
            _predefinedCode.Add("    that is mostly human readable. The generation and parsing of the ");
            _predefinedCode.Add("    various data types are done through the TypeConverter classes ");
            _predefinedCode.Add("    associated with the data types.");
            _predefinedCode.Add("    ");
            _predefinedCode.Add("    Example:");
            _predefinedCode.Add("    ");
            _predefinedCode.Add("    ... ado.net/XML headers & schema ...");
            _predefinedCode.Add("    <resheader name=\"resmimetype\">text/microsoft-resx</resheader>");
            _predefinedCode.Add("    <resheader name=\"version\">2.0</resheader>");
            _predefinedCode.Add("    <resheader name=\"reader\">System.Resources.ResXResourceReader, System.Windows.Forms, ...</resheader>");
            _predefinedCode.Add("    <resheader name=\"writer\">System.Resources.ResXResourceWriter, System.Windows.Forms, ...</resheader>");
            _predefinedCode.Add("    <data name=\"Name1\"><value>this is my long string</value><comment>this is a comment</comment></data>");
            _predefinedCode.Add("    <data name=\"Color1\" type=\"System.Drawing.Color, System.Drawing\">Blue</data>");
            _predefinedCode.Add("    <data name=\"Bitmap1\" mimetype=\"application/x-microsoft.net.object.binary.base64\">");
            _predefinedCode.Add("        <value>[base64 mime encoded serialized .NET Framework object]</value>");
            _predefinedCode.Add("    </data>");
            _predefinedCode.Add("    <data name=\"Icon1\" type=\"System.Drawing.Icon, System.Drawing\" mimetype=\"application/x-microsoft.net.object.bytearray.base64\">");
            _predefinedCode.Add("        <value>[base64 mime encoded string representing a byte array form of the .NET Framework object]</value>");
            _predefinedCode.Add("        <comment>This is a comment</comment>");
            _predefinedCode.Add("    </data>");
            _predefinedCode.Add("                ");
            _predefinedCode.Add("    There are any number of \"resheader\" rows that contain simple ");
            _predefinedCode.Add("    name/value pairs.");
            _predefinedCode.Add("    ");
            _predefinedCode.Add("    Each data row contains a name, and value. The row also contains a ");
            _predefinedCode.Add("    type or mimetype. Type corresponds to a .NET class that support ");
            _predefinedCode.Add("    text/value conversion through the TypeConverter architecture. ");
            _predefinedCode.Add("    Classes that don't support this are serialized and stored with the ");
            _predefinedCode.Add("    mimetype set.");
            _predefinedCode.Add("    ");
            _predefinedCode.Add("    The mimetype is used for serialized objects, and tells the ");
            _predefinedCode.Add("    ResXResourceReader how to depersist the object. This is currently not ");
            _predefinedCode.Add("    extensible. For a given mimetype the value must be set accordingly:");
            _predefinedCode.Add("    ");
            _predefinedCode.Add("    Note - application/x-microsoft.net.object.binary.base64 is the format ");
            _predefinedCode.Add("    that the ResXResourceWriter will generate, however the reader can ");
            _predefinedCode.Add("    read any of the formats listed below.");
            _predefinedCode.Add("    ");
            _predefinedCode.Add("    mimetype: application/x-microsoft.net.object.binary.base64");
            _predefinedCode.Add("    value   : The object must be serialized with ");
            _predefinedCode.Add("            : System.Serialization.Formatters.Binary.BinaryFormatter");
            _predefinedCode.Add("            : and then encoded with base64 encoding.");
            _predefinedCode.Add("    ");
            _predefinedCode.Add("    mimetype: application/x-microsoft.net.object.soap.base64");
            _predefinedCode.Add("    value   : The object must be serialized with ");
            _predefinedCode.Add("            : System.Runtime.Serialization.Formatters.Soap.SoapFormatter");
            _predefinedCode.Add("            : and then encoded with base64 encoding.");
            _predefinedCode.Add(string.Empty);
            _predefinedCode.Add("    mimetype: application/x-microsoft.net.object.bytearray.base64");
            _predefinedCode.Add("    value   : The object must be serialized into a byte array ");
            _predefinedCode.Add("            : using a System.ComponentModel.TypeConverter");
            _predefinedCode.Add("            : and then encoded with base64 encoding.");
            _predefinedCode.Add("    -->");
            _predefinedCode.Add("  <xsd:schema id=\"root\" xmlns=\"\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:msdata=\"urn:schemas-microsoft-com:xml-msdata\">");
            _predefinedCode.Add("    <xsd:element name=\"root\" msdata:IsDataSet=\"true\">");
            _predefinedCode.Add("      <xsd:complexType>");
            _predefinedCode.Add("        <xsd:choice maxOccurs=\"unbounded\">");
            _predefinedCode.Add("          <xsd:element name=\"metadata\">");
            _predefinedCode.Add("            <xsd:complexType>");
            _predefinedCode.Add("              <xsd:sequence>");
            _predefinedCode.Add("                <xsd:element name=\"value\" type=\"xsd:string\" minOccurs=\"0\" />");
            _predefinedCode.Add("              </xsd:sequence>");
            _predefinedCode.Add("              <xsd:attribute name=\"name\" type=\"xsd:string\" />");
            _predefinedCode.Add("              <xsd:attribute name=\"type\" type=\"xsd:string\" />");
            _predefinedCode.Add("              <xsd:attribute name=\"mimetype\" type=\"xsd:string\" />");
            _predefinedCode.Add("            </xsd:complexType>");
            _predefinedCode.Add("          </xsd:element>");
            _predefinedCode.Add("          <xsd:element name=\"assembly\">");
            _predefinedCode.Add("            <xsd:complexType>");
            _predefinedCode.Add("              <xsd:attribute name=\"alias\" type=\"xsd:string\" />");
            _predefinedCode.Add("              <xsd:attribute name=\"name\" type=\"xsd:string\" />");
            _predefinedCode.Add("            </xsd:complexType>");
            _predefinedCode.Add("          </xsd:element>");
            _predefinedCode.Add("          <xsd:element name=\"data\">");
            _predefinedCode.Add("            <xsd:complexType>");
            _predefinedCode.Add("              <xsd:sequence>");
            _predefinedCode.Add("                <xsd:element name=\"value\" type=\"xsd:string\" minOccurs=\"0\" msdata:Ordinal=\"1\" />");
            _predefinedCode.Add("                <xsd:element name=\"comment\" type=\"xsd:string\" minOccurs=\"0\" msdata:Ordinal=\"2\" />");
            _predefinedCode.Add("              </xsd:sequence>");
            _predefinedCode.Add("              <xsd:attribute name=\"name\" type=\"xsd:string\" msdata:Ordinal=\"1\" />");
            _predefinedCode.Add("              <xsd:attribute name=\"type\" type=\"xsd:string\" msdata:Ordinal=\"3\" />");
            _predefinedCode.Add("              <xsd:attribute name=\"mimetype\" type=\"xsd:string\" msdata:Ordinal=\"4\" />");
            _predefinedCode.Add("            </xsd:complexType>");
            _predefinedCode.Add("          </xsd:element>");
            _predefinedCode.Add("          <xsd:element name=\"resheader\">");
            _predefinedCode.Add("            <xsd:complexType>");
            _predefinedCode.Add("              <xsd:sequence>");
            _predefinedCode.Add("                <xsd:element name=\"value\" type=\"xsd:string\" minOccurs=\"0\" msdata:Ordinal=\"1\" />");
            _predefinedCode.Add("              </xsd:sequence>");
            _predefinedCode.Add("              <xsd:attribute name=\"name\" type=\"xsd:string\" use=\"required\" />");
            _predefinedCode.Add("            </xsd:complexType>");
            _predefinedCode.Add("          </xsd:element>");
            _predefinedCode.Add("        </xsd:choice>");
            _predefinedCode.Add("      </xsd:complexType>");
            _predefinedCode.Add("    </xsd:element>");
            _predefinedCode.Add("  </xsd:schema>");
            _predefinedCode.Add("  <resheader name=\"resmimetype\">");
            _predefinedCode.Add("    <value>text/microsoft-resx</value>");
            _predefinedCode.Add("  </resheader>");
            _predefinedCode.Add("  <resheader name=\"version\">");
            _predefinedCode.Add("    <value>2.0</value>");
            _predefinedCode.Add("  </resheader>");
            _predefinedCode.Add("  <resheader name=\"reader\">");
            _predefinedCode.Add("    <value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>");
            _predefinedCode.Add("  </resheader>");
            _predefinedCode.Add("  <resheader name=\"writer\">");
            _predefinedCode.Add("    <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>");
            _predefinedCode.Add("  </resheader>");
            _predefinedCode.Add("</root>");
        }
    };
}
