<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VkRadio.LowCode.AppGen.ArtefactGenerators.SqlCore\VkRadio.LowCode.AppGen.ArtefactGenerators.SqlCore.csproj" />
    <ProjectReference Include="..\VkRadio.LowCode.AppGen.Domain\VkRadio.LowCode.AppGen.Domain.csproj" />
  </ItemGroup>

</Project>
