<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VkRadio.LowCode.AppGen.ArtefactGenerators.Core\VkRadio.LowCode.AppGen.ArtefactGenerators.Core.csproj" />
    <ProjectReference Include="..\VkRadio.LowCode.AppGen.ArtefactGenerators.Ool.Core\VkRadio.LowCode.AppGen.ArtefactGenerators.Ool.Core.csproj" />
    <ProjectReference Include="..\VkRadio.LowCode.AppGen.ArtefactGenerators.Ool.CSharp.Core\VkRadio.LowCode.AppGen.ArtefactGenerators.Ool.CSharp.Core.csproj" />
    <ProjectReference Include="..\VkRadio.LowCode.AppGen.ArtefactGenerators.Sql.Core\VkRadio.LowCode.AppGen.ArtefactGenerators.Sql.Core.csproj" />
    <ProjectReference Include="..\VkRadio.LowCode.AppGen.Domain\VkRadio.LowCode.AppGen.Domain.csproj" />
  </ItemGroup>

</Project>
